# Generated by Django 4.0 on 2021-12-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_color_alter_sighting_options_alter_sighting_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Location',
        ),
    ]
