# Generated by Django 4.0 on 2021-12-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_color_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.ManyToManyField(to='main_app.Location'),
        ),
    ]
