# Generated by Django 4.0 on 2021-12-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='location',
            new_name='locations',
        ),
    ]
